name: Workflow happening before pull request
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn
      name: Lint
        run: yarn lint

